# **Pandas** **DataFrame**

**Creating** **Pandas** **DataFrames**

In [ ]:
# creating an empty DataFrame

import pandas as pd
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [ ]:
# creating a DataFrame form a list

import pandas as pd
lst = ['pandas', 'numpy', 'matplotlib']
df = pd.DataFrame(lst)
print(df)

            0
0      pandas
1       numpy
2  matplotlib

In [ ]:
# Creating DataFrame from lists of Numpy Array

import pandas as pd
import numpy as np

data = ([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(data, columns=['A','B','C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
# Creating a DataFrame from a List of Dictionaries

dict = {'name':['shilok','akash','bhavwesh','jaideep'],
        'marks':[99,98,97,96],
        'Grade':['A','B','C','D']}
df = pd.DataFrame(dict)
print(df)

       name  marks Grade
0    shilok     99     A
1     akash     98     B
2  bhavwesh     97     C
3   jaideep     96     D

In [ ]:
# Creating a DataFrame from Lists or Arrays
import pandas as pd

# initialize list of lists
data = [['tom', 10], ['nick', 15], ['juli', 14]]

# Create the pandas DataFrame
df = pd.DataFrame(data, columns=['Name', 'Age'])

print(df)

   Name  Age
0   tom   10
1  nick   15
2  juli   14

In [ ]:
#  DataFrame from List of Dictionaries
import pandas as pd

# Initialize data to lists.
data = [{'a': 1, 'b': 2, 'c': 3},
        {'a': 10, 'b': 20, 'c': 30}]

# Creates DataFrame.
df = pd.DataFrame(data)

print(df)

    a   b   c
0   1   2   3
1  10  20  30

In [ ]:
# DataFrame From Another DataFrame
original_df = pd.DataFrame({'Name': ['Tom', 'Nick', 'Krish', 'Jack'],
                            'Age': [20, 21, 19, 18]})

# selecting specific column
new_df = original_df[['Name']]
print(new_df)

    Name
0    Tom
1   Nick
2  Krish
3   Jack

In [ ]:
# DataFrame From Dictionary of Series

d = {'one': pd.Series([10, 20, 30, 40], index=['a','b','c','d']),
     'two': pd.Series([10, 20, 30, 40], index=['a','b','c','d'])}
df = pd.DataFrame(d)
print(df)

   one  two
a   10   10
b   20   20
c   30   30
d   40   40

In [ ]:
# DataFrame Using zip() function
Name = ['tom', 'krish', 'nick', 'juli']
Age = [25, 30, 26, 22]

list_of_tuples = list(zip(Name, Age))
df = pd.DataFrame(list_of_tuples, columns=['Name', 'Age'])
print(df)

    Name  Age
0    tom   25
1  krish   30
2   nick   26
3   juli   22

In [ ]:
# DataFrame With Explicit Index.
data = {'Name': ['Tom', 'Jack', 'nick', 'juli'],
        'marks': [99, 98, 95, 90]}
df = pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
print(df)

       Name  marks
rank1   Tom     99
rank2  Jack     98
rank3  nick     95
rank4  juli     90

**Pandas** **Dataframe** **Indexing**

In [ ]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
        'Age': [25, 30, 22, 35, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
print(df.index)  # Accessing the index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
# Set 'Name' column as the index
df_with_index = df.set_index('Name')
print(df_with_index)

         Age  Gender  Salary
Name
John      25    Male   50000
Alice     30  Female   55000
Bob       22    Male   40000
Eve       35  Female   70000
Charlie   28    Male   48000

In [ ]:
# Reset the index back to the default integer index
df_reset = df.reset_index()    #Old index becomes a new column, and a fresh 0–4 index is assigned.
print(df_reset)

   index     Name  Age  Gender  Salary
0      0     John   25    Male   50000
1      1    Alice   30  Female   55000
2      2      Bob   22    Male   40000
3      3      Eve   35  Female   70000
4      4  Charlie   28    Male   48000

In [ ]:
# With `drop=True`, the old index isn’t added as a column—only a new default index is set.
df_reset = df.reset_index(drop=True)
print(df_reset)

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [ ]:
# indexing by number
row = df.loc[2]
print(row)

Name        Bob
Age          22
Gender     Male
Salary    40000
Name: 2, dtype: object

In [ ]:
# Set 'Name' as the index
df = df.set_index('Name')

# Accessing "Alice" directly with loc(), because the rows is labeled by names instead of numbers.
row = df.loc['Alice']
print(row)

Age           30
Gender    Female
Salary     55000
Name: Alice, dtype: object

In [ ]:
# Changing the Index

df = df.reset_index()
df = df.set_index('Age')
print(df)

        Name  Gender  Salary
Age
25      John    Male   50000
30     Alice  Female   55000
22       Bob    Male   40000
35       Eve  Female   70000
28   Charlie    Male   48000

**Pandas** **DataFrames** **Accessing**

In [ ]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
        'Age': [25, 30, 22, 35, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
# Display the entire DataFrame
print(df)

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [ ]:
# Accessing Columns From DataFrame

# Access the 'Age' column
age_column = df['Age']
print(age_column)

0    25
1    30
2    22
3    35
4    28
Name: Age, dtype: int64

In [ ]:
# Accessing Rows by Index

# Access the row at index 1 (second row)
second_row = df.iloc[1]
print(second_row)

Name       Alice
Age           30
Gender    Female
Salary     55000
Name: 1, dtype: object

In [ ]:
# Accessing Multiple Rows or Columns

# Access the first three rows and the 'Name' and 'Age' columns
subset = df.loc[0:2, ['Name', 'Age']]
print(subset)

    Name  Age
0   John   25
1  Alice   30
2    Bob   22

In [ ]:
#  Accessing Rows Based on Conditions

# Access rows where 'Age' is greater than 25
filtered_data = df[df['Age'] > 25]
print(filtered_data)

      Name  Age  Gender  Salary
1    Alice   30  Female   55000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [ ]:
# Accessing Specific Cells with at and iat

# Access 'Salary' of row with label 2 (which is Bob)
salary_at = df.at[2, 'Salary']
print("Using .at:", salary_at)


# Access 'Salary' using integer positions: row 2, column 3
salary_iat = df.iat[2, 3]
print("Using .iat:", salary_iat)

Using .at: 40000
Using .iat: 40000

In [ ]:
# Accessing cells with loc and iloc functions

# Get Salary of row with label 2 (Bob)
print("Using .loc:", df.loc[2,'Salary'])

# Get all columns for Alice (row label = 1)
print("\nAlice's data (loc):\n", df.loc[1])

Using .loc: 40000

Alice's data (loc):
 Name       Alice
Age           30
Gender    Female
Salary     55000
Name: 1, dtype: object

In [ ]:
# Get Salary using integer position row=2, col=3
print("Using .iloc:", df.iloc[2, 3])

# Get all columns for Alice (row 1)
print("\nAlice's data (iloc):\n", df.iloc[1])

Using .iloc: 40000

Alice's data (iloc):
 Name       Alice
Age           30
Gender    Female
Salary     55000
Name: 1, dtype: object

**Indexing** **and** **Selecting** **Data** **with** **Pandas**

In [ ]:
#                                                           1-  Indexing Data using the [] Operator

data = pd.read_csv('/content/nba.csv', index_col= 'Name')
print('Dataset')
display(data.head(5))

Dataset

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [ ]:
age_column = data["Age"]
print("\nSingle Column selected from Dataset")
display(age_column.head(5))

Single Column selected from Dataset

Name
Avery Bradley    25.0
Jae Crowder      25.0
John Holland     27.0
R.J. Hunter      22.0
Jonas Jerebko    29.0
Name: Age, dtype: float64

In [ ]:
#  Selecting Multiple Columns

first = data[["Age", "College", "Salary"]]
print("\nMultiple Columns selected from Dataset")
display(first.head(5))

Multiple Columns selected from Dataset

                Age            College     Salary
Name
Avery Bradley  25.0              Texas  7730337.0
Jae Crowder    25.0          Marquette  6796117.0
John Holland   27.0  Boston University        NaN
R.J. Hunter    22.0      Georgia State  1148640.0
Jonas Jerebko  29.0                NaN  5000000.0

In [ ]:
#                                                                   2 - Indexing with .loc[]

import pandas as pd
data = pd.read_csv("/content/nba.csv", index_col="Name")

# Selecting a Single Row by Label
row = data.loc["Avery Bradley"]
print(row)

Team        Boston Celtics
Number                 0.0
Position                PG
Age                   25.0
Height                 6-2
Weight               180.0
College              Texas
Salary           7730337.0
Name: Avery Bradley, dtype: object

In [ ]:
#  Selecting Multiple Rows by Label

rows = data.loc[["Avery Bradley", "R.J. Hunter"]]
print(rows)

                         Team  Number Position   Age Height  Weight  \
Name
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0

                     College     Salary
Name
Avery Bradley          Texas  7730337.0
R.J. Hunter    Georgia State  1148640.0

In [ ]:
# Selecting Specific Rows and Columns

selection = data.loc[["Avery Bradley", "R.J. Hunter", "Jonas Jerebko"], ["Team", "Number", "Position", "Salary"]]
print(selection)

                         Team  Number Position     Salary
Name
Avery Bradley  Boston Celtics     0.0       PG  7730337.0
R.J. Hunter    Boston Celtics    28.0       SG  1148640.0
Jonas Jerebko  Boston Celtics     8.0       PF  5000000.0

In [ ]:
# Selecting All Rows and Specific Columns

selection = data.loc[:, ["Team", "Position", "Salary"]]
print(selection)

                         Team Position     Salary
Name
Avery Bradley  Boston Celtics       PG  7730337.0
Jae Crowder    Boston Celtics       SF  6796117.0
John Holland   Boston Celtics       SG        NaN
R.J. Hunter    Boston Celtics       SG  1148640.0
Jonas Jerebko  Boston Celtics       PF  5000000.0
...                       ...      ...        ...
Shelvin Mack        Utah Jazz       PG  2433333.0
Raul Neto           Utah Jazz       PG   900000.0
Tibor Pleiss        Utah Jazz        C  2900000.0
Jeff Withey         Utah Jazz        C   947276.0
NaN                       NaN      NaN        NaN

[458 rows x 3 columns]

In [ ]:
#                                                       3 - Indexing with .iloc[ ]

import pandas as pd
data = pd.read_csv("/content/nba.csv", index_col="Name")

# Selecting a Single Row by Position
row = data.iloc[3]
print(row)

Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object

In [ ]:
# Selecting Multiple Rows by Position

rows = data.iloc[[3, 5, 7]]
print(rows)

                        Team  Number Position   Age Height  Weight  \
Name
R.J. Hunter   Boston Celtics    28.0       SG  22.0    6-5   185.0
Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0
Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0

                    College      Salary
Name
R.J. Hunter   Georgia State   1148640.0
Amir Johnson            NaN  12000000.0
Kelly Olynyk        Gonzaga   2165160.0

In [ ]:
# Selecting Specific Rows and Columns by Position

selection = data.iloc[[3, 4], [1, 2]]
print(selection)

               Number Position
Name
R.J. Hunter      28.0       SG
Jonas Jerebko     8.0       PF

In [ ]:
# Selecting All Rows and Specific Columns by Position
selection = data.iloc[:, [1, 2]]
print(selection)

               Number Position
Name
Avery Bradley     0.0       PG
Jae Crowder      99.0       SF
John Holland     30.0       SG
R.J. Hunter      28.0       SG
Jonas Jerebko     8.0       PF
...               ...      ...
Shelvin Mack      8.0       PG
Raul Neto        25.0       PG
Tibor Pleiss     21.0        C
Jeff Withey      24.0        C
NaN               NaN      NaN

[458 rows x 2 columns]

In [ ]:
# Selecting specific Rows and all Columns by Position

selection = data.iloc[[3, 4], :]
print(selection)

                         Team  Number Position   Age Height  Weight  \
Name
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

                     College     Salary
Name
R.J. Hunter    Georgia State  1148640.0
Jonas Jerebko            NaN  5000000.0

In [ ]:
#                                                     4 -  Other Useful Indexing Methods

# head()

df = data.head(5)
print(df)

                         Team  Number Position   Age Height  Weight  \
Name
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0
John Holland   Boston Celtics    30.0       SG  27.0    6-5   205.0
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

                         College     Salary
Name
Avery Bradley              Texas  7730337.0
Jae Crowder            Marquette  6796117.0
John Holland   Boston University        NaN
R.J. Hunter        Georgia State  1148640.0
Jonas Jerebko                NaN  5000000.0

In [ ]:
# tail

df = data.tail(5)
print(df)

                   Team  Number Position   Age Height  Weight College  \
Name
Shelvin Mack  Utah Jazz     8.0       PG  26.0    6-3   203.0  Butler
Raul Neto     Utah Jazz    25.0       PG  24.0    6-1   179.0     NaN
Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0     NaN
Jeff Withey   Utah Jazz    24.0        C  26.0    7-0   231.0  Kansas
NaN                 NaN     NaN      NaN   NaN    NaN     NaN     NaN

                 Salary
Name
Shelvin Mack  2433333.0
Raul Neto      900000.0
Tibor Pleiss  2900000.0
Jeff Withey    947276.0
NaN                 NaN

In [ ]:
# .at[]

df = data.at["Avery Bradley", "Salary"]
print(df)

7730337.0

In [ ]:
# .query()

print()
df = data.query("Age > 25 and College == 'Duke' ")
print(df)

                                    Team  Number Position   Age Height  \
Name
Lance Thomas             New York Knicks    42.0       SF  28.0    6-8
Elton Brand           Philadelphia 76ers    42.0       PF  37.0    6-9
JJ Redick           Los Angeles Clippers     4.0       SG  31.0    6-4
Mike Dunleavy              Chicago Bulls    34.0       SG  35.0    6-9
Dahntay Jones        Cleveland Cavaliers    30.0       SG  35.0    6-6
Miles Plumlee            Milwaukee Bucks    18.0        C  27.0   6-11
Luol Deng                     Miami Heat     9.0       SF  31.0    6-9
Josh McRoberts                Miami Heat     4.0       PF  29.0   6-10
Kyle Singler       Oklahoma City Thunder     5.0       SF  28.0    6-8
Gerald Henderson  Portland Trail Blazers     9.0       SG  28.0    6-5
Mason Plumlee     Portland Trail Blazers    24.0        C  26.0   6-11

                  Weight College      Salary
Name
Lance Thomas       235.0    Duke   1636842.0
Elton Brand        254.0    Duke         NaN
JJ Redick          190.0    Duke   7085000.0
Mike Dunleavy      230.0    Duke   4500000.0
Dahntay Jones      225.0    Duke         NaN
Miles Plumlee      249.0    Duke   2109294.0
Luol Deng          220.0    Duke  10151612.0
Josh McRoberts     240.0    Duke   5543725.0
Kyle Singler       228.0    Duke   4500000.0
Gerald Henderson   215.0    Duke   6000000.0
Mason Plumlee      235.0    Duke   1415520.0

**Pandas** **DataFrames** **Slicing**

In [ ]:
# Create a Custom Dataframe

import pandas as pd

# List of Pakistani players
player_list = [
    ['Babar Azam', 29, 72, 8500000],
    ['Shaheen Afridi', 24, 78, 6500000],
    ['Shadab Khan', 26, 70, 5000000],
    ['Mohammad Rizwan', 32, 68, 7200000],
    ['Fakhar Zaman', 34, 75, 4800000],
    ['Haris Rauf', 31, 74, 5500000],
    ['Sarfraz Ahmed', 37, 73, 4300000]
]

# Creating DataFrame
df = pd.DataFrame(player_list, columns=['Name', 'Age', 'Weight', 'Salary'])
print(df)

              Name  Age  Weight   Salary
0       Babar Azam   29      72  8500000
1   Shaheen Afridi   24      78  6500000
2      Shadab Khan   26      70  5000000
3  Mohammad Rizwan   32      68  7200000
4     Fakhar Zaman   34      75  4800000
5       Haris Rauf   31      74  5500000
6    Sarfraz Ahmed   37      73  4300000

In [ ]:
#                            Slicing Using iloc[] (Integer-Based Indexing)

# Slicing Rows in dataframe
df1 = df.iloc[0:4]
print(df1)

              Name  Age  Weight   Salary
0       Babar Azam   29      72  8500000
1   Shaheen Afridi   24      78  6500000
2      Shadab Khan   26      70  5000000
3  Mohammad Rizwan   32      68  7200000

In [ ]:
# Slicing Columns in dataframe

df1 = df.iloc[:, 0:2]

print(df1)

              Name  Age
0       Babar Azam   29
1   Shaheen Afridi   24
2      Shadab Khan   26
3  Mohammad Rizwan   32
4     Fakhar Zaman   34
5       Haris Rauf   31
6    Sarfraz Ahmed   37

In [ ]:
# Selecting a Specific Cell in a Pandas DataFrame

value = df.iloc[2, 3]
print("Specific Cell Value:", value)

Specific Cell Value: 5000000

In [ ]:
# Using Boolean Conditions in a Pandas DataFrame

data = df[df['Age'] > 35].iloc[:, :]
print("\nFiltered Data based on Age > 35:\n", data)

Filtered Data based on Age > 35:
                Age  Weight   Salary
Name
Sarfraz Ahmed   37      73  4300000

In [ ]:
#                                               Slicing Using loc[]

# Slicing Rows in Dataframe

df.set_index('Name', inplace=True)
custom = df.loc['Shaheen Afridi':'Fakhar Zaman']
print(custom)

                 Age  Weight   Salary
Name
Shaheen Afridi    24      78  6500000
Shadab Khan       26      70  5000000
Mohammad Rizwan   32      68  7200000
Fakhar Zaman      34      75  4800000

In [ ]:
# Selecting Specified cell in Dataframe

value = df.loc['Shadab Khan', 'Salary']
print("\nValue of the Specific Cell (V.Kohli, Salary):", value)

Value of the Specific Cell (V.Kohli, Salary): 5000000

**Pandas** **Dataframe** **Filtering** **with** **multiple** **conditions**

In [ ]:
# Creating a sample dataframe to proceed further

# import module
import pandas as pd

# assign data
dataFrame = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ', '  ROSS    ', 'CHANDLER', ' JOEY    ', ' Elaris   '],

                          'Age': [30, 35, 37, 33, 34, 30, 23],

                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000, 85000],

                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',  'IT', 'ARTIST', 'ANALYST']})

# display dataframe
display(dataFrame)

         Name  Age  Salary          JOB
0    RACHEL     30  100000     DESIGNER
1    MONICA     35   93000         CHEF
2    PHOEBE     37   88000        MASUS
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT
5    JOEY       30   95000       ARTIST
6   Elaris      23   85000      ANALYST

In [ ]:
# Get all rows where Salary >= 100000, Age < 40, and Job starts with 'D', then print only Name and Job using loc

display(dataFrame.loc[(dataFrame['Salary']>=100000) & (dataFrame['Age']< 40) & (dataFrame['JOB'].str.startswith('D')), ['Name', 'JOB']])

        Name       JOB
0   RACHEL    DESIGNER

In [ ]:
# Filter Pandas Dataframe Using NumPy

# import module
import pandas as pd
import numpy as np

# assign data
dataFrame = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ',
                                   '  ROSS    ', 'CHANDLER', ' JOEY    '],

                          'Age': [30, 35, 37, 33, 34, 30],

                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],

                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})

# filter dataframe
filtered_values = np.where((dataFrame['Salary']>=100000) & (dataFrame['Age']< 40) & (dataFrame['JOB'].str.startswith('D')))
print(filtered_values)
display(dataFrame.loc[filtered_values])

(array([0]),)

        Name  Age  Salary       JOB
0   RACHEL     30  100000  DESIGNER

In [ ]:
# Filter Pandas Dataframe Using Query (eval and query works only with columns)

# import module
import pandas as pd

# assign data
dataFrame = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ',
                                   '  ROSS    ', 'CHANDLER', ' JOEY    '],

                          'Age': [30, 35, 37, 33, 34, 30],

                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],

                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})

# filter dataframe
display(dataFrame.query('Salary  <= 100000 & Age < 40 & JOB.str.startswith("C").values'))

        Name  Age  Salary   JOB
1   MONICA     35   93000  CHEF

In [ ]:
# Pandas Boolean indexing multiple conditions standard way ("Boolean indexing" works with values in a column only

# import module
import pandas as pd

# assign data
dataFrame = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ',
                                   '  ROSS    ', 'CHANDLER', ' JOEY    '],

                          'Age': [30, 35, 37, 33, 34, 30],

                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],

                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})

# filter dataframe
display(dataFrame[(dataFrame['Salary']>=100000) & (dataFrame['Age']<40) & dataFrame['JOB'].str.startswith('P')][['Name','Age','Salary']])

         Name  Age  Salary
3    ROSS       33  120000

In [ ]:
# Eval multiple conditions  ("eval" and "query" works only with columns )

# import module
import pandas as pd

# assign data
dataFrame = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ',
                                   '  ROSS    ', 'CHANDLER', ' JOEY    '],

                          'Age': [30, 35, 37, 33, 34, 30],

                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],

                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})

# filter dataframe
display(dataFrame[dataFrame.eval("Salary <=100000 & (Age <40) & JOB.str.startswith('A').values")])

        Name  Age  Salary     JOB
5   JOEY       30   95000  ARTIST

**Pandas** **DataFrames** **Merging**, **Joining** **and** **Concatenating**

In [ ]:
#                                         Concatenating DataFrames

# 1. Concatenating DataFrame using .concat()

import pandas as pd

data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd']}

data2 = {'Name': ['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'],
         'Age': [17, 14, 12, 52],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1, index=[0, 1, 2, 3])
df1 = pd.DataFrame(data2, index=[4, 5, 6, 7])
print(df, "\n\n", df1)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

      Name  Age    Address Qualification
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [ ]:
frames = [df, df1]

res1 = pd.concat(frames)
res1

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [ ]:
# 2. Concatenating DataFrames by Setting Logic on Axes
# choose whether to take the Union (join='outer') or Intersection (join='inner') of columns

import pandas as pd

data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd'],
         'Mobile No': [97, 91, 58, 76]}

data2 = {'Name': ['Gaurav', 'Anuj', 'Dhiraj', 'Hitesh'],
         'Age': [22, 32, 12, 52],
         'Address': ['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
         'Qualification': ['MCA', 'Phd', 'Bcom', 'B.hons'],
         'Salary': [1000, 2000, 3000, 4000]}

df = pd.DataFrame(data1, index=[0, 1, 2, 3])

df1 = pd.DataFrame(data2, index=[2, 3, 6, 7])

print(df, "\n\n", df1)

     Name  Age    Address Qualification  Mobile No
0     Jai   27     Nagpur           Msc         97
1  Princi   24     Kanpur            MA         91
2  Gaurav   22  Allahabad           MCA         58
3    Anuj   32    Kannuaj           Phd         76

      Name  Age    Address Qualification  Salary
2  Gaurav   22  Allahabad           MCA    1000
3    Anuj   32    Kannuaj           Phd    2000
6  Dhiraj   12  Allahabad          Bcom    3000
7  Hitesh   52    Kannuaj        B.hons    4000

In [ ]:
# set axes join = inner for intersection of dataframe which keeps only the common columns.

res2 = pd.concat([df, df1], axis=1, join='inner')
res2

In [ ]:
res3 = pd.concat([df,df1], axis=1, join = 'outer')
res3

,Name,Age,Address,Qualification,Mobile No,Name,Age,Address,Qualification,Salary
0,Jai,27.0,Nagpur,Msc,97.0,NaN,NaN,NaN,NaN,NaN
1,Princi,24.0,Kanpur,MA,91.0,NaN,NaN,NaN,NaN,NaN
2,Gaurav,22.0,Allahabad,MCA,58.0,Gaurav,22.0,Allahabad,MCA,1000.0
3,Anuj,32.0,Kannuaj,Phd,76.0,Anuj,32.0,Kannuaj,Phd,2000.0
6,NaN,NaN,NaN,NaN,NaN,Dhiraj,12.0,Allahabad,Bcom,3000.0
7,NaN,NaN,NaN,NaN,NaN,Hitesh,52.0,Kannuaj,B.hons,4000.0

In [ ]:
res2 = pd.concat([df, df1], axis=1, sort=False)
res2

,Name,Age,Address,Qualification,Mobile No,Name,Age,Address,Qualification,Salary
0,Jai,27.0,Nagpur,Msc,97.0,NaN,NaN,NaN,NaN,NaN
1,Princi,24.0,Kanpur,MA,91.0,NaN,NaN,NaN,NaN,NaN
2,Gaurav,22.0,Allahabad,MCA,58.0,Gaurav,22.0,Allahabad,MCA,1000.0
3,Anuj,32.0,Kannuaj,Phd,76.0,Anuj,32.0,Kannuaj,Phd,2000.0
6,NaN,NaN,NaN,NaN,NaN,Dhiraj,12.0,Allahabad,Bcom,3000.0
7,NaN,NaN,NaN,NaN,NaN,Hitesh,52.0,Kannuaj,B.hons,4000.0

In [ ]:
# 3. Concatenating DataFrames by Ignoring Indexes

import pandas as pd

data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd'],
        'Mobile No': [97, 91, 58, 76]}

data2 = {'Name':['Gaurav', 'Anuj', 'Dhiraj', 'Hitesh'],
        'Age':[22, 32, 12, 52],
        'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons'],
        'Salary':[1000, 2000, 3000, 4000]}

df = pd.DataFrame(data1,index=[0, 1, 2, 3])
df1 = pd.DataFrame(data2, index=[2, 3, 6, 7])
print(df, "\n\n", df1)

     Name  Age    Address Qualification  Mobile No
0     Jai   27     Nagpur           Msc         97
1  Princi   24     Kanpur            MA         91
2  Gaurav   22  Allahabad           MCA         58
3    Anuj   32    Kannuaj           Phd         76

      Name  Age    Address Qualification  Salary
2  Gaurav   22  Allahabad           MCA    1000
3    Anuj   32    Kannuaj           Phd    2000
6  Dhiraj   12  Allahabad          Bcom    3000
7  Hitesh   52    Kannuaj        B.hons    4000

In [ ]:
res = pd.concat([df, df1], ignore_index=True)
res

     Name  Age    Address Qualification  Mobile No  Salary
0     Jai   27     Nagpur           Msc       97.0     NaN
1  Princi   24     Kanpur            MA       91.0     NaN
2  Gaurav   22  Allahabad           MCA       58.0     NaN
3    Anuj   32    Kannuaj           Phd       76.0     NaN
4  Gaurav   22  Allahabad           MCA        NaN  1000.0
5    Anuj   32    Kannuaj           Phd        NaN  2000.0
6  Dhiraj   12  Allahabad          Bcom        NaN  3000.0
7  Hitesh   52    Kannuaj        B.hons        NaN  4000.0

In [ ]:
frames = [df, df1 ]
res = pd.concat(frames, keys=['x', 'y'])
res

       Name  Age    Address Qualification  Mobile No  Salary
x 0     Jai   27     Nagpur           Msc       97.0     NaN
  1  Princi   24     Kanpur            MA       91.0     NaN
  2  Gaurav   22  Allahabad           MCA       58.0     NaN
  3    Anuj   32    Kannuaj           Phd       76.0     NaN
y 2  Gaurav   22  Allahabad           MCA        NaN  1000.0
  3    Anuj   32    Kannuaj           Phd        NaN  2000.0
  6  Dhiraj   12  Allahabad          Bcom        NaN  3000.0
  7  Hitesh   52    Kannuaj        B.hons        NaN  4000.0

In [ ]:
# 5. Concatenating Mixed DataFrames and Series

import pandas as pd

data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

df = pd.DataFrame(data1,index=[0, 1, 2, 3])

s1 = pd.Series([1000, 2000, 3000, 4000], name='Salary')

print(df, "\n\n", s1)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

 0    1000
1    2000
2    3000
3    4000
Name: Salary, dtype: int64

In [ ]:
res = pd.concat([df, s1], axis=1)
res

     Name  Age    Address Qualification  Salary
0     Jai   27     Nagpur           Msc    1000
1  Princi   24     Kanpur            MA    2000
2  Gaurav   22  Allahabad           MCA    3000
3    Anuj   32    Kannuaj           Phd    4000

In [ ]:
#                                         Merging DataFrame

# 1. Merging DataFrames Using One Key
import pandas as pd
data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}
data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)
df1 = pd.DataFrame(data2)
print(df, "\n\n", df1)

  key    Name  Age
0  K0     Jai   27
1  K1  Princi   24
2  K2  Gaurav   22
3  K3    Anuj   32

   key    Address Qualification
0  K0     Nagpur         Btech
1  K1     Kanpur           B.A
2  K2  Allahabad          Bcom
3  K3    Kannuaj        B.hons

In [ ]:
res = pd.merge(df, df1, on='key')
res

  key    Name  Age    Address Qualification
0  K0     Jai   27     Nagpur         Btech
1  K1  Princi   24     Kanpur           B.A
2  K2  Gaurav   22  Allahabad          Bcom
3  K3    Anuj   32    Kannuaj        B.hons

In [ ]:
# 2. Merging DataFrames Using Multiple Keys

import pandas as pd
data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K1', 'K0', 'K1'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}
data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K0', 'K0', 'K0'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)
df1 = pd.DataFrame(data2)
print(df, "\n\n", df1)

  key key1    Name  Age
0  K0   K0     Jai   27
1  K1   K1  Princi   24
2  K2   K0  Gaurav   22
3  K3   K1    Anuj   32

   key key1    Address Qualification
0  K0   K0     Nagpur         Btech
1  K1   K0     Kanpur           B.A
2  K2   K0  Allahabad          Bcom
3  K3   K0    Kannuaj        B.hons

In [ ]:
res1 = pd.merge(df, df1, on=['key', 'key1'])

res1

  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K2   K0  Gaurav   22  Allahabad          Bcom

In [ ]:
# Merging DataFrames Using the how Argument

import pandas as pd
data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K1', 'K0', 'K1'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}
data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K0', 'K0', 'K0'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}
df = pd.DataFrame(data1)
df1 = pd.DataFrame(data2)
print(df, "\n\n", df1)

  key key1    Name  Age
0  K0   K0     Jai   27
1  K1   K1  Princi   24
2  K2   K0  Gaurav   22
3  K3   K1    Anuj   32

   key key1    Address Qualification
0  K0   K0     Nagpur         Btech
1  K1   K0     Kanpur           B.A
2  K2   K0  Allahabad          Bcom
3  K3   K0    Kannuaj        B.hons

In [ ]:
# we set how = 'left' in order to use keys from left frame only.
res = pd.merge(df, df1, how='left', on=['key', 'key1'])
res

  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K1   K1  Princi   24        NaN           NaN
2  K2   K0  Gaurav   22  Allahabad          Bcom
3  K3   K1    Anuj   32        NaN           NaN

In [ ]:
# set how = 'right' in order to use keys from right frame only

res1 = pd.merge(df, df1, how='right', on=['key', 'key1'])
res1

  key key1    Name   Age    Address Qualification
0  K0   K0     Jai  27.0     Nagpur         Btech
1  K1   K0     NaN   NaN     Kanpur           B.A
2  K2   K0  Gaurav  22.0  Allahabad          Bcom
3  K3   K0     NaN   NaN    Kannuaj        B.hons

In [ ]:
# we set how = 'outer' in order to get union of keys from dataframes

res2 = pd.merge(df, df1, how='outer', on=['key', 'key1'])
res2

  key key1    Name   Age    Address Qualification
0  K0   K0     Jai  27.0     Nagpur         Btech
1  K1   K0     NaN   NaN     Kanpur           B.A
2  K1   K1  Princi  24.0        NaN           NaN
3  K2   K0  Gaurav  22.0  Allahabad          Bcom
4  K3   K0     NaN   NaN    Kannuaj        B.hons
5  K3   K1    Anuj  32.0        NaN           NaN

In [ ]:
res3 = pd.merge(df,df1, how = 'inner', on=['key', 'key1'])
res3

  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K2   K0  Gaurav   22  Allahabad          Bcom

In [ ]:
#                                                       Joining DataFrame

# 1. Joining DataFrames Using .join()

import pandas as pd

data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32]}
data2 = {'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons']}
df = pd.DataFrame(data1,index=['K0', 'K1', 'K2', 'K3'])
df1 = pd.DataFrame(data2, index=['K0', 'K2', 'K3', 'K4'])

print(df, "\n\n", df1)

      Name  Age
K0     Jai   27
K1  Princi   24
K2  Gaurav   22
K3    Anuj   32

       Address Qualification
K0  Allahabad           MCA
K2    Kannuaj           Phd
K3  Allahabad          Bcom
K4    Kannuaj        B.hons

In [ ]:
#  using .join()
res = df.join(df1)
res

      Name  Age    Address Qualification
K0     Jai   27  Allahabad           MCA
K1  Princi   24        NaN           NaN
K2  Gaurav   22    Kannuaj           Phd
K3    Anuj   32  Allahabad          Bcom

In [ ]:
#  use how = 'outer' in order to get union.

res1 = df.join(df1, how='outer')
res1

      Name   Age    Address Qualification
K0     Jai  27.0  Allahabad           MCA
K1  Princi  24.0        NaN           NaN
K2  Gaurav  22.0    Kannuaj           Phd
K3    Anuj  32.0  Allahabad          Bcom
K4     NaN   NaN    Kannuaj        B.hons

In [ ]:
# 2. Joining DataFrames Using the "on" Argument

import pandas as pd

data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Key':['K0', 'K1', 'K2', 'K3']}
data2 = {'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)
df1 = pd.DataFrame(data2, index=['K0', 'K2', 'K3', 'K4'])


print(df, "\n\n", df1)

     Name  Age Key
0     Jai   27  K0
1  Princi   24  K1
2  Gaurav   22  K2
3    Anuj   32  K3

       Address Qualification
K0  Allahabad           MCA
K2    Kannuaj           Phd
K3  Allahabad          Bcom
K4    Kannuaj        B.hons

In [ ]:
# using .join with “on” argument.
res2 = df.join(df1, on='Key')
res2

     Name  Age Key    Address Qualification
0     Jai   27  K0  Allahabad           MCA
1  Princi   24  K1        NaN           NaN
2  Gaurav   22  K2    Kannuaj           Phd
3    Anuj   32  K3  Allahabad          Bcom

In [ ]:
# 3. Joining DataFrames with Different Index Levels (Multi-Index)
import pandas as pd

data1 = {'Name':['Jai', 'Princi', 'Gaurav'],
        'Age':[27, 24, 22]}
data2 = {'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kanpur'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1, index=pd.Index(['K0', 'K1', 'K2'], name='key'))

index = pd.MultiIndex.from_tuples([('K0', 'Y0'), ('K1', 'Y1'),
                                   ('K2', 'Y2'), ('K2', 'Y3')],
                                   names=['key', 'Y'])

df1 = pd.DataFrame(data2, index= index)
print(df, "\n\n", df1)

       Name  Age
key
K0      Jai   27
K1   Princi   24
K2   Gaurav   22

           Address Qualification
key Y
K0  Y0  Allahabad           MCA
K1  Y1    Kannuaj           Phd
K2  Y2  Allahabad          Bcom
    Y3     Kanpur        B.hons

In [ ]:
result = df.join(df1, how='inner')
result

          Name  Age    Address Qualification
key Y
K0  Y0     Jai   27  Allahabad           MCA
K1  Y1  Princi   24    Kannuaj           Phd
K2  Y2  Gaurav   22  Allahabad          Bcom
    Y3  Gaurav   22     Kanpur        B.hons

**Pandas** **DataFrame** **Sorting**

In [ ]:
                                                # 1. Sorting a DataFrame by a Single Column

import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],          # here it is already sorted.
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Age')
print(sorted_df)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [ ]:
# If we need the sorting to be in descending order simply pass ascending=False

import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],'Age': [25, 30, 35, 40],'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Age',ascending=False)
print(sorted_df)

      Name  Age  Score
3    David   40     80
2  Charlie   35     95
1      Bob   30     90
0    Alice   25     85

In [ ]:
#                                              2. Sorting a DataFrame by Multiple Columns

import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)

sorted_df = df.sort_values(by=['Age', 'Score'])
print(sorted_df)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [ ]:
# By default sort_values() places NaN values at the end
import pandas as pd
data_with_nan = {"Name": ["Alice", "Bob", "Charlie", "David"],"Age": [28, 22, None, 22]}
df_nan = pd.DataFrame(data_with_nan)

sorted_df = df_nan.sort_values(by="Age")
print(sorted_df)

      Name   Age
1      Bob  22.0
3    David  22.0
0    Alice  28.0
2  Charlie   NaN

In [ ]:
#                                                   3. Sorting DataFrame with Missing Values


# If we need them at the top, we can use the na_position parameter.
import pandas as pd
data_with_nan = {"Name": ["Alice", "Bob", "Charlie", "David"],"Age": [28, 22, None, 22]}
df_nan = pd.DataFrame(data_with_nan)

sorted_df = df_nan.sort_values(by="Age", na_position="first")
print(sorted_df)

      Name   Age
2  Charlie   NaN
1      Bob  22.0
3    David  22.0
0    Alice  28.0

In [ ]:
#                                                           4. Sorting by Index

#  By default, sort_index() sorts the DataFrame based on the index in ascending order.
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)

df_sorted_by_index = df.sort_index()
print(df_sorted_by_index)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [ ]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)

df_sorted_by_index = df.sort_index(ascending= False)
print(df_sorted_by_index)

      Name  Age  Score
3    David   40     80
2  Charlie   35     95
1      Bob   30     90
0    Alice   25     85

In [ ]:
#                                                  5. Choosing a Sorting Algorithm


# 1. QuickSort (kind='quicksort'):

import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [28, 22, 25, 22, 28],
    "Score": [85, 90, 95, 80, 88]
}
df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Age', kind='quicksort' )
print(sorted_df)

      Name  Age  Score
1      Bob   22     90
3    David   22     80
2  Charlie   25     95
0    Alice   28     85
4      Eve   28     88

In [ ]:
# MergeSort (kind='mergesort'):

import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [28, 22, 25, 22, 28],
    "Score": [85, 90, 95, 80, 88]
}
df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Age', kind='mergesort')
print(sorted_df)

      Name  Age  Score
1      Bob   22     90
3    David   22     80
2  Charlie   25     95
0    Alice   28     85
4      Eve   28     88

In [ ]:
# 3. HeapSort (kind= 'heapsort'):

import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [28, 22, 25, 22, 28],
    "Score": [85, 90, 95, 80, 88]
}
df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Age', kind='heapsort')
print(sorted_df)

      Name  Age  Score
1      Bob   22     90
3    David   22     80
2  Charlie   25     95
4      Eve   28     88
0    Alice   28     85

In [ ]:
# 6. Applying Custom Sorting Logic

import pandas as pd
data = {
    "Name": ["Alice", "Bob", "charlie", "David", "eve"],
    "Age": [28, 22, 25, 22, 28],
    "Score": [85, 90, 95, 80, 88]
}
df = pd.DataFrame(data)
sorted_df = df.sort_values(by='Name', key=lambda col: col.str.lower())
print(sorted_df)

      Name  Age  Score
0    Alice   28     85
1      Bob   22     90
2  charlie   25     95
3    David   22     80
4      eve   28     88

**Pivot** **Table** **in** **Pandas**

In [ ]:
# Let's first create a dataframe that includes Sales of Fruits.

# importing pandas
import pandas as pd

# creating dataframe
df = pd.DataFrame({'Product': ['Carrots', 'Broccoli', 'Banana', 'Banana',
                               'Beans', 'Orange', 'Broccoli', 'Banana'],
                   'Category': ['Vegetable', 'Vegetable', 'Fruit', 'Fruit',
                                'Vegetable', 'Fruit', 'Vegetable', 'Fruit'],
                   'Quantity': [8, 5, 3, 4, 5, 9, 11, 8],
                   'Amount': [270, 239, 617, 384, 626, 610, 62, 90]})
df

    Product   Category  Quantity  Amount
0   Carrots  Vegetable         8     270
1  Broccoli  Vegetable         5     239
2    Banana      Fruit         3     617
3    Banana      Fruit         4     384
4     Beans  Vegetable         5     626
5    Orange      Fruit         9     610
6  Broccoli  Vegetable        11      62
7    Banana      Fruit         8      90

In [ ]:
# Create a Pivot Table in Pandas

# Example 1: Get the Total Sales of Each Product
pivot = df.pivot_table(index=['Product'], values=['Amount'],aggfunc='sum')
print(pivot)

          Amount
Product
Banana      1091
Beans        626
Broccoli     301
Carrots      270
Orange       610

In [ ]:
# Example 2: Get the Total Sales of Each Category

# creating pivot table of total
# sales category-wise aggfunc = 'sum'
pivot = df.pivot_table(index=['Category'], values=['Amount'], aggfunc='sum')
print(pivot)

           Amount
Category
Fruit        1701
Vegetable    1197

In [ ]:
# Example 3: Get Total Sales by Category and Product Both.

pivot = df.pivot_table(index=['Product', 'Category'],
                       values=['Amount'], aggfunc='sum')
print(pivot)

                    Amount
Product  Category
Banana   Fruit        1091
Beans    Vegetable     626
Broccoli Vegetable     301
Carrots  Vegetable     270
Orange   Fruit         610

In [ ]:
# Example 4: Get the Mean, Median, Minimum Sale by Category

pivot = df.pivot_table(index=['Category'], values=['Amount'], aggfunc={'mean', 'median', 'min'})
print(pivot)

           Amount
             mean median min
Category
Fruit      425.25  497.0  90
Vegetable  299.25  254.5  62

In [ ]:
# Example 5: Get the Mean, Median, Minimum Sale by Product

pivot = df.pivot_table(index = ['Product'], values = ['Amount'], aggfunc={'mean', 'median', 'min'})
print(pivot)

              Amount
                mean median  min
Product
Banana    363.666667  384.0   90
Beans     626.000000  626.0  626
Broccoli  150.500000  150.5   62
Carrots   270.000000  270.0  270
Orange    610.000000  610.0  610