# **Data** **Input** **and** **Output** (**I / O**)

**Read** **CSV** **Files** **with** **Pandas**

In [ ]:
# import the Pandas library. then using Pandas load this data into a DataFrame as follows

import pandas as pd
df = pd.read_csv('/content/people_data.csv')
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [ ]:
#                                               Features in Pandas read_csv

# 1. Read specific columns using read_csv

df = pd.read_csv('/content/people_data.csv', usecols=['First Name', 'Email'])
df

  First Name                       Email
0     Shelby        elijah57@example.net
1    Phillip       bethany14@example.com
2   Kristine       bthompson@example.com
3    Yesenia   kaitlinkaiser@example.com
4       Lori  buchananmanuel@example.net

In [ ]:
#2.  Setting an Index Column (index_col)

df = pd.read_csv('/content/people_data.csv', index_col='First Name')
df

,Last Name,Sex,Email,Date of birth,Job Title
First Name,,,,,
Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [ ]:
# 3. Handling Missing Values Using read_csv

df = pd.read_csv("/content/people_data.csv", na_values=["N/A", "Unknown"])

In [ ]:
# 4. Reading CSV Files with Different Delimiters

import pandas as pd

# Sample data stored in a multi-line string
data = """totalbill_tip, sex:smoker, day_time, size
16.99, 1.01:Female|No, Sun, Dinner, 2
10.34, 1.66, Male, No|Sun:Dinner, 3
21.01:3.5_Male, No:Sun, Dinner, 3
23.68, 3.31, Male|No, Sun_Dinner, 2
24.59:3.61, Female_No, Sun, Dinner, 4
25.29, 4.71|Male, No:Sun, Dinner, 4"""

# Save the data to a CSV file
with open("sample.csv", "w") as file:
    file.write(data)
print(data)

totalbill_tip, sex:smoker, day_time, size
16.99, 1.01:Female|No, Sun, Dinner, 2
10.34, 1.66, Male, No|Sun:Dinner, 3
21.01:3.5_Male, No:Sun, Dinner, 3
23.68, 3.31, Male|No, Sun_Dinner, 2
24.59:3.61, Female_No, Sun, Dinner, 4
25.29, 4.71|Male, No:Sun, Dinner, 4

In [ ]:
# Load the CSV file using pandas with multiple delimiters
df = pd.read_csv('/content/sample.csv',
                 sep='[:, |_]',  # Define the delimiters
                 engine='python')  # Use Python engine for regex separators
df

,totalbill,tip,Unnamed: 2,sex,smoker,Unnamed: 5,day,time,Unnamed: 8,size
16.99,NaN,1.01,Female,No,NaN,Sun,NaN,Dinner,NaN,2.0
10.34,NaN,1.66,NaN,Male,NaN,No,Sun,Dinner,NaN,3.0
21.01,3.50,Male,NaN,No,Sun,NaN,Dinner,NaN,3.0,NaN
23.68,NaN,3.31,NaN,Male,No,NaN,Sun,Dinner,NaN,2.0
24.59,3.61,NaN,Female,No,NaN,Sun,NaN,Dinner,NaN,4.0
25.29,NaN,4.71,Male,NaN,No,Sun,NaN,Dinner,NaN,4.0

In [ ]:
# 5. Using nrows in read_csv()

df = pd.read_csv('/content/people_data.csv', nrows=3)
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath

In [ ]:
# 6. Using skiprows in read_csv()
df = pd.read_csv('/content/people_data.csv')
print('Previous data:')
print(df)

df1 = pd.read_csv('/content/people_data.csv', skiprows=2)
print('after skipping 2 rows')
print(df1)

Previous data:
  First Name Last Name     Sex                       Email Date of birth  \
0     Shelby   Terrell    Male        elijah57@example.net    1945-10-26
1    Phillip   Summers  Female       bethany14@example.com    1910-03-24
2   Kristine    Travis    Male       bthompson@example.com    1992-07-02
3    Yesenia  Martinez    Male   kaitlinkaiser@example.com    2017-08-03
4       Lori      Todd    Male  buchananmanuel@example.net    1938-12-01

            Job Title
0     Games developer
1      Phytotherapist
2           Homeopath
3   Market researcher
4  Veterinary surgeon
after skipping 2 rows
    Phillip   Summers Female       bethany14@example.com  1910-03-24  \
0  Kristine    Travis   Male       bthompson@example.com  1992-07-02
1   Yesenia  Martinez   Male   kaitlinkaiser@example.com  2017-08-03
2      Lori      Todd   Male  buchananmanuel@example.net  1938-12-01

       Phytotherapist
0           Homeopath
1   Market researcher
2  Veterinary surgeon

In [ ]:
df = pd.read_csv("/content/people_data.csv", parse_dates=["Date of birth"])
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   First Name     5 non-null      object
 1   Last Name      5 non-null      object
 2   Sex            5 non-null      object
 3   Email          5 non-null      object
 4   Date of birth  5 non-null      datetime64[ns]
 5   Job Title      5 non-null      object
dtypes: datetime64[ns](1), object(5)
memory usage: 372.0+ bytes
None

In [ ]:
url = "https://media.geeksforgeeks.org/wp-content/uploads/20241121154629307916/people_data.csv"
df = pd.read_csv(url)
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

**Writing** **data** **to** **CSV** **Files**

In [ ]:
# taking sample data to convert DataFrame to CSV.

import pandas as pd

# list of name, degree, score
nme = ["aparna", "pankaj", "sudhir", "Geeku"]
deg = ["MBA", "BCA", "M.Tech", "MBA"]
scr = [90, 40, 80, 98]

# dictionary of lists
dict = {'name': nme, 'degree': deg, 'score': scr}

df = pd.DataFrame(dict)

# export a Dataframe to a CSV file using df.to_csv().
df.to_csv('file1.csv')

In [ ]:
df = pd.read_csv('/content/file1.csv')
df

   Unnamed: 0    name  degree  score
0           0  aparna     MBA     90
1           1  pankaj     BCA     40
2           2  sudhir  M.Tech     80
3           3   Geeku     MBA     98

In [ ]:
# saving the dataframe with no header and no index number
df.to_csv('/content/file2.csv', header=False, index=False)
df

   0  aparna     MBA  90
0  1  pankaj     BCA  40
1  2  sudhir  M.Tech  80
2  3   Geeku     MBA  98

In [ ]:
# Save the CSV file to a Specified Location

# saving the dataframe
df.to_csv(r'E:\Desktop\MEDICAL IMAGING FLIES\ALL COURSES\4-Python')

**Export** **Pandas** **dataframe** **to** **a** **CSV** **file**

In [ ]:
# Creating a Sample DataFrame
import pandas as pd

scores = {'Name': ['a', 'b', 'c', 'd'],
          'Score': [90, 80, 95, 20]}

df = pd.DataFrame(scores)
print(df)

  Name  Score
0    a     90
1    b     80
2    c     95
3    d     20

In [ ]:
# 1. Basic Export

df.to_csv("Tanisha_Maheshwari2.csv")

In [ ]:
# 2. Remove Index Column

df.to_csv('Tanisha_Maheshwari3.csv', index = False)

In [ ]:
# 3. Export only selected column

df.to_csv("Tanisha_Maheshwari1.csv", columns = ['Name'])

In [ ]:
# 4. Exclude Header Row

df.to_csv('data_analyst.csv', header = False)

In [ ]:
# 5. Handling Missing Values

df.to_csv("data.csv", na_rep = 'nothing')

In [ ]:
df.to_csv("data1.csv", sep ='\t')

**Read JSON Files with Pandas**

In [ ]:
import pandas as pd
import json

data = {"One": {"0": 60, "1": 60, "2": 60, "3": 45, "4": 45, "5": 60},
        "Two": {"0": 110, "1": 117, "2": 103, "3": 109, "4": 117, "5": 102}}

json_data = json.dumps(data)

df_normalize = pd.json_normalize(json.loads(json_data))
print("\nDataFrame using JSON module and `pd.json_normalize()` method:")
df_normalize

DataFrame using JSON module and `pd.json_normalize()` method:

,One.0,One.1,One.2,One.3,One.4,One.5,Two.0,Two.1,Two.2,Two.3,Two.4,Two.5
0,60,60,60,45,45,60,110,117,103,109,117,102