# **Data** **Cleaning** **in** **Pandas**

**Handling** **Missing** **Data**

1- Checking Missing Values in Pandas

In [ ]:
# Using isnull()

# Example 1: Finding Missing Values in a DataFrame
import pandas as pd
import numpy as np

d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)

mv = df.isnull()

print(mv)

   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [ ]:
# Example 2: Filtering Data Based on Missing Values

import pandas as pd
d = pd.read_csv("/content/drive/MyDrive/employees.csv")

bool_series = pd.isnull(d["Gender"])
missing_gender_data = d[bool_series]
print(missing_gender_data)

    First Name Gender  Start Date Last Login Time  Salary  Bonus %  \
20        Lois    NaN   4/22/1995         7:18 PM   64714    4.934
22      Joshua    NaN    3/8/2012         1:58 AM   90816   18.816
27       Scott    NaN   7/11/1991         6:58 PM  122367    5.218
31       Joyce    NaN   2/20/2005         2:40 PM   88657   12.752
41   Christine    NaN   6/28/2015         1:08 AM   66582   11.308
..         ...    ...         ...             ...     ...      ...
961    Antonio    NaN   6/18/1989         9:37 PM  103050    3.050
972     Victor    NaN   7/28/2006         2:49 PM   76381   11.159
985    Stephen    NaN   7/10/1983         8:10 PM   85668    1.909
989     Justin    NaN   2/10/1991         4:58 PM   38344    3.794
995      Henry    NaN  11/23/2014         6:09 AM  132483   16.655

    Senior Management                  Team
20               True                 Legal
22               True       Client Services
27              False                 Legal
31              False               Product
41               True  Business Development
..                ...                   ...
961             False                 Legal
972              True                 Sales
985             False                 Legal
989             False                 Legal
995             False          Distribution

[145 rows x 8 columns]

In [ ]:
#2. Using isna()

import pandas as pd
import numpy as np

data = {'Name': ['Amit', 'Sita', np.nan, 'Raj'],
        'Age': [25, np.nan, 22, 28]}

df = pd.DataFrame(data)

# Check for missing values using isna()
print(df.isna())

    Name    Age
0  False  False
1  False   True
2   True  False
3  False  False

In [ ]:
# 3. Checking for Non-Missing Values Using notnull()


# Example 1: Identifying Non-Missing Values in a DataFrame
import pandas as pd
import numpy as np

d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)

nmv = df.notnull()

print(nmv)

   First Score  Second Score  Third Score
0         True          True        False
1         True          True         True
2        False          True         True
3         True         False         True

In [ ]:
# Example 2: Filtering Data with Non-Missing Values

import pandas as pd
d = pd.read_csv("/content/drive/MyDrive/employees.csv")
nmg = pd.notnull(d["Gender"])
nmgd= d[nmg]
nmgd

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [ ]:
d.shape

(1000, 8)

2 - Filling Missing Values in Pandas

In [ ]:
# 1. Using fillna()

# Example 1: Fill Missing Values with Zero
import pandas as pd
import numpy as np

d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)
df.fillna(0)

   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [ ]:
# Example 2: Fill with Previous Value (Forward Fill)
import pandas as pd
import numpy as np

d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)
df.fillna(method='pad')

/tmp/ipython-input-3659861427.py:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='pad')

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2         90.0          56.0         80.0
3         95.0          56.0         98.0

In [ ]:
df.ffill()     # df.ffill() → Forward fill (same as fillna(method='pad'))

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2         90.0          56.0         80.0
3         95.0          56.0         98.0

In [ ]:
# Example 3: Fill with Next Value (Backward Fill)
import pandas as pd
import numpy as np

d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)

df.fillna(method='bfill')

/tmp/ipython-input-3067090891.py:10: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

   First Score  Second Score  Third Score
0        100.0          30.0         40.0
1         90.0          45.0         40.0
2         95.0          56.0         80.0
3         95.0           NaN         98.0

In [ ]:
df.bfill()           # df.bfill() → Backward fill (same as fillna(method='bfill'))

   First Score  Second Score  Third Score
0        100.0          30.0         40.0
1         90.0          45.0         40.0
2         95.0          56.0         80.0
3         95.0           NaN         98.0

In [ ]:
# Example 4: Fill NaN Values with 'No Gender

import pandas as pd
import numpy as np
d = pd.read_csv("/content/drive/MyDrive/employees.csv")

d[10:25]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,NaN
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12/7/1986,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
20,Lois,NaN,4/22/1995,7:18 PM,64714,4.934,True,Legal
21,Matthew,Male,9/5/1995,2:12 AM,100612,13.645,False,Marketing
22,Joshua,NaN,3/8/2012,1:58 AM,90816,18.816,True,Client Services
23,NaN,Male,6/14/2012,4:19 PM,125792,5.042,NaN,NaN
24,John,Male,7/1/1992,10:08 PM,97950,13.873,False,Client Services

In [ ]:
# Now we are going to fill all the null values in Gender column with "No Gender"
d["Gender"].fillna('No Gender', inplace = True)
d[10:25]   # range

/tmp/ipython-input-984902648.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d["Gender"].fillna('No Gender', inplace = True)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,NaN
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12/7/1986,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
20,Lois,No Gender,4/22/1995,7:18 PM,64714,4.934,True,Legal
21,Matthew,Male,9/5/1995,2:12 AM,100612,13.645,False,Marketing
22,Joshua,No Gender,3/8/2012,1:58 AM,90816,18.816,True,Client Services
23,NaN,Male,6/14/2012,4:19 PM,125792,5.042,NaN,NaN
24,John,Male,7/1/1992,10:08 PM,97950,13.873,False,Client Services

In [ ]:
# previous code explanantion

'''
⚠️ Warning:

FutureWarning: A value is trying to be set on a copy of a DataFrame or Series
through chained assignment using an inplace method.
This inplace method will never work in pandas 3.0


✅ Recommended Solutions:

Instead of using inplace=True on a column slice, use one of these safe approaches:

🔹 Option 1: Assign back to the column
df["Gender"] = df["Gender"].fillna("No Gender")

🔹 Option 2: Use dictionary-style with fillna on full DataFrame
df.fillna({"Gender": "No Gender"}, inplace=True)

🔹 Option 3: If you really want inplace column operation (not recommended)
df.loc[:, "Gender"].fillna("No Gender", inplace=True)
'''

In [ ]:
# 2. Using replace()

import pandas as pd
import numpy as np

data = pd.read_csv("/content/drive/MyDrive/employees.csv")
data[10:25]

# replace the all NaN value in the data frame with -99 value.
data.replace(to_replace=np.nan, value=-99)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,-99
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,-99,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [ ]:
# 3. Using interpolate()

import pandas as pd

df = pd.DataFrame({"A": [12, 4, 5, None, 1],
                   "B": [None, 2, 54, 3, None],
                   "C": [20, 16, None, 3, 8],
                   "D": [14, 3, None, None, 6]})
print(df)

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   NaN   NaN
3   NaN   3.0   3.0   NaN
4   1.0   NaN   8.0   6.0

In [ ]:
df.interpolate(method ='linear', limit_direction ='forward')

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   9.5   4.0
3   3.0   3.0   3.0   5.0
4   1.0   3.0   8.0   6.0

3 - Dropping Missing Values in Pandas

In [ ]:
# 1. Dropping Rows with At Least One Null Value

import pandas as pd
import numpy as np

dict = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, 40, 80, 98],
        'Fourth Score': [np.nan, np.nan, np.nan, 65]}
df = pd.DataFrame(dict)

df.dropna()

   First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0           98          65.0

In [ ]:
# 2. Dropping Rows with All Null Values

dict = {'First Score': [100, np.nan, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, np.nan, 80, 98],
        'Fourth Score': [np.nan, np.nan, np.nan, 65]}
df = pd.DataFrame(dict)

df.dropna(how='all')

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0         52.0           NaN
2          NaN          45.0         80.0           NaN
3         95.0          56.0         98.0          65.0

In [ ]:
# 3. Dropping Columns with At Least One Null Value
dict = {'First Score': [100, np.nan, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, np.nan, 80, 98],
        'Fourth Score': [60, 67, 68, 65]}
df = pd.DataFrame(dict)
df.dropna(axis=1)

In [ ]:
# 4. Dropping Rows with Missing Values in CSV Files

import pandas as pd
d = pd.read_csv("/content/drive/MyDrive/employees.csv")

nd = d.dropna(axis=0, how='any')

print("Old data frame length:", len(d))
print("New data frame length:", len(nd))
print("Rows with at least one missing value:", (len(d) - len(nd)))

Old data frame length: 1000
New data frame length: 764
Rows with at least one missing value: 236

**Removing** **Duplicates**

In [ ]:
# basic example to see how drop_duplicates() works.

import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Alice", "David"],
    "Age": [25, 30, 25, 40],
    "City": ["NY", "LA", "NY", "Chicago"]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

df_cleaned = df.drop_duplicates()
print("\nModified DataFrame (no duplicates)")
print(df_cleaned)

Original DataFrame:
    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
2  Alice   25       NY
3  David   40  Chicago

Modified DataFrame (no duplicates)
    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
3  David   40  Chicago

In [ ]:
# 1. Dropping Duplicates Based on Specific Columns

import pandas as pd
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Alice', 'David'],
    'Age': [25, 30, 25, 40],
    'City': ['NY', 'LA', 'SF', 'Chicago']
})
df_cleaned = df.drop_duplicates(subset=["Name"])
print(df_cleaned)

    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
3  David   40  Chicago

In [ ]:
# 2. Keeping the Last Occurrence of Duplicates

import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Alice', 'David'],
    'Age': [25, 30, 25, 40],
    'City': ['NY', 'LA', 'NY', 'Chicago']
})
df_cleaned= df.drop_duplicates(keep='last')
print(df_cleaned)

    Name  Age     City
1    Bob   30       LA
2  Alice   25       NY
3  David   40  Chicago

In [ ]:
# 3. Dropping All Duplicates
import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Alice', 'David'],
    'Age': [25, 30, 25, 40],
    'City': ['NY', 'LA', 'NY', 'Chicago']
})
df_cleaned = df.drop_duplicates(keep=False)
print(df_cleaned)

    Name  Age     City
1    Bob   30       LA
3  David   40  Chicago

In [ ]:
# 4. Modifying the Original DataFrame Directly

import pandas as pd
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Alice', 'David'],
    'Age': [25, 30, 25, 40],
    'City': ['NY', 'LA', 'NY', 'Chicago']
})
df.drop_duplicates(inplace=True)
print(df)

    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
3  David   40  Chicago

In [ ]:
# 5. Dropping Duplicates Based on Partially Identical Columns

import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Alice", "David", "Bob"],
    "Age": [25, 30, 25, 40, 30],
    "City": ["NY", "LA", "NY", "Chicago", "LA"]
}

df = pd.DataFrame(data)
df_cleaned = df.drop_duplicates(subset=["Name", "City"])
print(df_cleaned)

    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
3  David   40  Chicago

**Pandas** **Change** **Datatype**

In [ ]:
# 1. Using astype() method

import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
        'Age': [25, 30, 22, 35, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
# Convert 'Age' column to float type
df['Age'] = df['Age'].astype(float)
print(df.dtypes)

Name       object
Age       float64
Gender     object
Salary      int64
dtype: object

In [ ]:
# 2. Converting a Column to a DateTime Type

import pandas as pd
data = {
    'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
    'Age': [25, 30, 22, 35, 28],
    'Position': ['Engineer', 'Manager', 'Analyst', 'HR', 'Developer'],
    'Salary': [50000, 60000, 45000, 55000, 70000],
    'Join Date': ['2023-01-10', '2022-05-15', '2021-08-22', '2020-12-05', '2019-07-19']}

df  = pd.DataFrame(data)
# Convert 'Join Date' to datetime type
d = df['Join Date'] = pd.to_datetime(df['Join Date'])
print('datatype of all columns', df.dtypes)

datatype of all columns Name                 object
Age                   int64
Position             object
Salary                int64
Join Date    datetime64[ns]
dtype: object

In [ ]:
# before/after conversion

print('before conversion join date:')
print(data['Join Date'])
print('\n after conversion join date:')
print(d)

before conversion join date:
['2023-01-10', '2022-05-15', '2021-08-22', '2020-12-05', '2019-07-19']

 after conversion join date:
0   2023-01-10
1   2022-05-15
2   2021-08-22
3   2020-12-05
4   2019-07-19
Name: Join Date, dtype: datetime64[ns]

In [ ]:
# 3. Changing Multiple Columns' Data Types

# Convert 'Age' to float and 'Salary' to string
df = df.astype({'Age': 'float64', 'Salary': 'str'})
print(df.dtypes)
print(df)

Name                 object
Age                 float64
Position             object
Salary               object
Join Date    datetime64[ns]
dtype: object
      Name   Age   Position Salary  Join Date
0     John  25.0   Engineer  50000 2023-01-10
1    Alice  30.0    Manager  60000 2022-05-15
2      Bob  22.0    Analyst  45000 2021-08-22
3      Eve  35.0         HR  55000 2020-12-05
4  Charlie  28.0  Developer  70000 2019-07-19

**Drop** **Empty** **Columns** **in** **DataFrame**

In [ ]:
# Create a Sample DataFrame:

import numpy as np
import pandas as pd

df = pd.DataFrame({'FirstName': ['Vipul', 'Ashish', 'Milan'],
                      "Gender": ["", "", ""],
                         "Age": [0, 0, 0]})
df['Department'] = np.nan

print(df)

  FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

In [ ]:
# Example 1: Remove All Null Value Columns

import numpy as np
import pandas as pd

df = pd.DataFrame({'FirstName': ['Vipul', 'Ashish', 'Milan'],
                            "Gender": ["", "", ""],
                            "Age": [0, 0, 0]})

df['Department'] = np.nan
display(df)

df.dropna(how='all', axis=1, inplace=True)
display(df)             #This will remove Department, since it is fully NaN.

  FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

  FirstName Gender  Age
0     Vipul           0
1    Ashish           0
2     Milan           0

In [ ]:
# Example 2: Replace Empty Strings with Null and then Drop Null Columns
import numpy as np
import pandas as pd

df = pd.DataFrame({'FirstName': ['Vipul', 'Ashish', 'Milan'],
                            "Gender": ["", "", ""],
                            "Age": [0, 0, 0]})
df['Department'] = np.nan
display(df)
nan_value = float("NaN")
df.replace("",nan_value, inplace=True)    #Now Gender column will also be removed (since it was all empty).

df.dropna(how='all', axis=1, inplace=True)
display(df)

  FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

/tmp/ipython-input-1517282979.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("",nan_value, inplace=True)

  FirstName  Age
0     Vipul    0
1    Ashish    0
2     Milan    0

In [ ]:
# Example 3: Replace Zeros with Null and Drop Null Columns

import numpy as np
import pandas as pd

df = pd.DataFrame({'FirstName': ['Vipul', 'Ashish', 'Milan'],
                            "Gender": ["", "", ""],
                            "Age": [0, 0, 0]})

df['Department'] = np.nan
display(df)

df.replace(0, np.nan, inplace=True)

df.dropna(how='all', axis=1, inplace=True)

display(df)

  FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

  FirstName Gender
0     Vipul
1    Ashish
2     Milan

In [ ]:
# Example 4: Replace Both Zeros and Empty Strings with Null and Drop Null Columns

import numpy as np
import pandas as pd

df = pd.DataFrame({'FirstName': ['Vipul', 'Ashish', 'Milan'],
                            "Gender": ["", "", ""],
                            "Age": [0, 0, 0]})

df['Department'] = np.nan
display(df)

df.replace(["", 0], np.nan, inplace=True)

df.dropna(how='all', axis=1, inplace=True)

display(df)

  FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

/tmp/ipython-input-2953209102.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(["", 0], np.nan, inplace=True)

  FirstName
0     Vipul
1    Ashish
2     Milan

**String manipulations in Pandas DataFrame**

In [ ]:
# Create a String Dataframe using Pandas

import pandas as pd
import numpy as np

data = {'Names': ['Gulshan', 'Shashank', 'Bablu', 'Abhishek', 'Anand', np.nan, 'Pratap'],
        'City': ['Delhi', 'Mumbai', 'Kolkata', 'Delhi', 'Chennai', 'Bangalore', 'Hyderabad']}

df = pd.DataFrame(data)
print(df)

      Names       City
0   Gulshan      Delhi
1  Shashank     Mumbai
2     Bablu    Kolkata
3  Abhishek      Delhi
4     Anand    Chennai
5       NaN  Bangalore
6    Pratap  Hyderabad

In [ ]:
# Change Column Datatype
print(df.astype('string'))

      Names       City
0   Gulshan      Delhi
1  Shashank     Mumbai
2     Bablu    Kolkata
3  Abhishek      Delhi
4     Anand    Chennai
5      <NA>  Bangalore
6    Pratap  Hyderabad

In [ ]:
# lower():
print(df['Names'].str.lower())

0     gulshan
1    shashank
2       bablu
3    abhishek
4       anand
5         NaN
6      pratap
Name: Names, dtype: object

In [ ]:
# upper():
print(df['Names'].str.upper())

0     GULSHAN
1    SHASHANK
2       BABLU
3    ABHISHEK
4       ANAND
5         NaN
6      PRATAP
Name: Names, dtype: object

In [ ]:
# strip():
print(df['Names'].str.strip())

0     Gulshan
1    Shashank
2       Bablu
3    Abhishek
4       Anand
5         NaN
6      Pratap
Name: Names, dtype: object

In [ ]:

# spilt():
print(df['Names'].str.split('a'))

0      [Gulsh, n]
1    [Sh, sh, nk]
2        [B, blu]
3      [Abhishek]
4        [An, nd]
5             NaN
6      [Pr, t, p]
Name: Names, dtype: object

In [ ]:
# len():
print(df['Names'].str.len())

0    7.0
1    8.0
2    5.0
3    8.0
4    5.0
5    NaN
6    6.0
Name: Names, dtype: float64

In [ ]:
# cat(sep=' '):
print(df['Names'].str.cat(sep=' '))

Gulshan Shashank Bablu Abhishek Anand Pratap

In [ ]:
print(df['City'].str.get_dummies())

   Bangalore  Chennai  Delhi  Hyderabad  Kolkata  Mumbai
0          0        0      1          0        0       0
1          0        0      0          0        0       1
2          0        0      0          0        1       0
3          0        0      1          0        0       0
4          0        1      0          0        0       0
5          1        0      0          0        0       0
6          0        0      0          1        0       0

In [ ]:
# startswith(pattern):
print(df['Names'].str.startswith('G'))

0     True
1    False
2    False
3    False
4    False
5      NaN
6    False
Name: Names, dtype: object

In [ ]:
# endswith(pattern):
print(df['Names'].str.endswith('h'))

0    False
1    False
2    False
3    False
4    False
5      NaN
6    False
Name: Names, dtype: object

In [ ]:
# Python replace(a,b):
print(df['Names'].str.replace('Gulshan', 'Gaurav'))

0      Gaurav
1    Shashank
2       Bablu
3    Abhishek
4       Anand
5         NaN
6      Pratap
Name: Names, dtype: object

In [ ]:
# Python repeat(value):
print(df['Names'].str.repeat(4))

0        GulshanGulshanGulshanGulshan
1    ShashankShashankShashankShashank
2                BabluBabluBabluBablu
3    AbhishekAbhishekAbhishekAbhishek
4                AnandAnandAnandAnand
5                                 NaN
6            PratapPratapPratapPratap
Name: Names, dtype: object

In [ ]:
# Python count(pattern):
print(df['Names'].str.count('a'))

0    1.0
1    2.0
2    1.0
3    0.0
4    1.0
5    NaN
6    2.0
Name: Names, dtype: float64

In [ ]:
# Python find(pattern):
print(df['Names'].str.find('a'))

0    5.0
1    2.0
2    1.0
3   -1.0
4    2.0
5    NaN
6    2.0
Name: Names, dtype: float64

In [ ]:
# findall(pattern):
print(df['Names'].str.findall('a'))

0       [a]
1    [a, a]
2       [a]
3        []
4       [a]
5       NaN
6    [a, a]
Name: Names, dtype: object

In [ ]:
# islower():
print(df['Names'].str.islower())

0    False
1    False
2    False
3    False
4    False
5      NaN
6    False
Name: Names, dtype: object

In [ ]:
# isupper()
print(df['Names'].str.isupper())

0    False
1    False
2    False
3    False
4    False
5      NaN
6    False
Name: Names, dtype: object

In [ ]:
# isnumeric():
print(df['Names'].str.isnumeric())

0    False
1    False
2    False
3    False
4    False
5      NaN
6    False
Name: Names, dtype: object

In [ ]:
# swapcase():
print(df['Names'].str.swapcase())

0     gULSHAN
1    sHASHANK
2       bABLU
3    aBHISHEK
4       aNAND
5         NaN
6      pRATAP
Name: Names, dtype: object

**Detect Mixed Data Types and Fix it**

In [ ]:
# Example of mixed datatype:
import pandas as pd
data_frame = pd.DataFrame( [['tom', 10], ['nick', '15'], ['juli', 14.8]], columns=['Name', 'Age'])  # So it becomes a mixed data type column.

In [ ]:
# to detect mixed datatype: You cannot rely only on info() (because it won’t show mixed properly).
# 'infer_dtype()' checks the type of data in each column.This helps us identify if the column contains 'mixed','string','integer', etc.

print("\nDetecting Data Types:")
for column in data_frame.columns:
    print(column, ":", pd.api.types.infer_dtype(data_frame[column]))

Detecting Data Types:
Name : string
Age : mixed-integer

In [ ]:
# Fixing  Mixed Types: There are 2 main ways:

# 1 - Using astype() function:

# Transforming mixed data types to single data type
data_frame[column] = data_frame[column].astype(int)
# Traverse data frame to detect data types after fix
for column in data_frame.columns:
    print(column,':',pd.api.types.infer_dtype(data_frame[column]))

Name : string
Age : integer

In [ ]:
# 2 - Using to_numeric() function:

# Transforming mixed data types to single data type
data_frame[column] = data_frame[column].apply(lambda x: pd.to_numeric(x, errors = 'ignore'))
# Traverse data frame to detect data types after fix
for column in data_frame.columns:
  print(pd.api.types.infer_dtype(data_frame[column]))

string
integer

/tmp/ipython-input-3611291079.py:4: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  data_frame[column] = data_frame[column].apply(lambda x: pd.to_numeric(x, errors = 'ignore'))